---
title: "Nested Positions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{nested-positions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ggplot2)
library(ggdibbler)
library(patchwork)
```



# Nested position examples
```{r nestedexample, eval=FALSE}
ggplot(smaller_diamonds, aes(carat, after_stat(count), fill = cut)) +
  geom_density(aes(colour=cut), position = "stack") #ggplot
ggplot(smaller_uncertain_diamonds, aes(carat, after_stat(count), fill = cut)) +
  geom_density_sample(aes(colour = after_stat(fill)),
                          position = "stack_identity", alpha=0.15)+
  theme(palette.fill.discrete = "viridis",
        palette.colour.discrete = "viridis")
```

```{r dodgeerrorabrs, eval=FALSE}
# If you want to dodge bars and errorbars, you need to manually
# specify the dodge width
# ggplot
p <- ggplot(df, aes(trt, resp, fill = group))
p +
  geom_col(position = "dodge") +
  geom_errorbar(aes(ymin = lower, ymax = upper), position = "dodge", width = 0.25)
# NEED NESTED POSITION - POSITION_DODGE_IDENTITY OR EVEN POSITION_DODGE_DODGE
# THIS DOES POSITION_DODGE_DODGE THE OTHER WAY AROUND (MAIN PLOT INSIDE OF DIST)
# ggdibbler
q <- ggplot(uncertain_df, aes(trt, resp, fill = group))
q +
  geom_col_sample(position = "dodge_identity") +
  geom_errorbar_sample(aes(ymin = lower, ymax = upper), 
                       position = "dodge_identity", width = 0.25)
# 
# Because the bars and errorbars have different widths
# we need to specify how wide the objects we are dodging are
# ggplot
dodge <- position_dodge(width=0.9)
dodge2 <- position_dodge_identity(width=0.9)
p +
  geom_col(position = dodge) +
  geom_errorbar(aes(ymin = lower, ymax = upper), position = dodge, width = 0.25)
# ggdibbler
q +
  geom_col_sample(position = dodge2) +
  geom_errorbar_sample(aes(ymin = lower, ymax = upper), position = dodge2, width = 0.25)

```
